_target_: src.models.gdr_module.GDRModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.graph_diffusion.GDR
  input_size: 4
  hidden_size: 64
  output_size: 2
  diffusion_component: 'default'

# compile model for faster training with pytorch 2.0
compile: false
