_target_: src.models.grsn.GRSN

num_sample: 3
num_sub_nodes: 5

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

graph_conv:
  _target_: src.models.components.graph_conv.MyGraphConv
#  _target_: src.models.components.graph_attn.MyGraphAttn
  input_size: 4
  hidden_size: 64
  output_size: 64

graph_decoder:
  _target_: src.models.components.graph_decoder.GraphDecoder

graph_classifier:
  _target_: src.models.components.graph_classifier.GraphClassifier
  input_size: ${model.num_sample}*${model.graph_conv.output_size}
  output_size: 1


# compile model for faster training with pytorch 2.0
compile: false
