_target_: src.models.baseline.ocgtl.OCGTL

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
#  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 100
  gamma: 0.5

dim_features: 42
num_trans: 6
dim_targets: 2
num_layers: 4
hidden_dim: 32
norm_layer: 'gn'
bias: False
aggregation: 'add'

# compile model for faster training with pytorch 2.0
compile: false
