_target_: src.models.basic_gnn.BasicGNN

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.00001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

graph_conv:
  _target_: src.models.components.graph_sage.MyGraphSage
  input_size: 4
  hidden_size: 32
  output_size: 32
  aggregator_type: 'pool'
  dropout: 0.2

graph_classifier:
  _target_: src.models.components.graph_classifier.GraphClassifier
  input_size: ${model.graph_conv.output_size}
  output_size: 1
  dropout: 0.2

# compile model for faster training with pytorch 2.0
compile: false
