_target_: src.models.gr_classification.GRClassification

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0003
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

graph_conv:
  _target_: src.models.components.graph_sgconv.MySGConv
  input_size: 4
  hidden_size: 64
  output_size: 64

graph_decoder:
  _target_: src.models.components.graph_decoder.GraphDecoder

graph_classifier:
  _target_: src.models.components.graph_classifier.GraphClassifier
  input_size: 64
  output_size: 1

# compile model for faster training with pytorch 2.0
compile: false
