# @package _global_

defaults:
  - _self_
  - data: gdr # choose datamodule with `test_dataloader()` for evaluation
  - model: gaussian_gdr2
  - logger: csv
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "logs/train/runs/2023-11-17_08-02-15/checkpoints/epoch_000.ckpt"
